# Generated by Django 2.1.2 on 2018-11-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_question', models.TextField(max_length=500)),
                ('card_answer', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('statistic_success', models.IntegerField(default=0)),
                ('statistic_unsuccess', models.IntegerField(default=0)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
            ],
            options={
                'db_table': 'statictic',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
                ('topic_time', models.TimeField(default=0)),
                ('topic_dateView', models.DateField(default=0)),
                ('topic_dateTest', models.DateField(default=0)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Topic'),
        ),
    ]
